version: "3.8"

services:
  db:
    image: postgres:13
    container_name: hw28-docker
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: hw28
      POSTGRES_PASSWORD: hw28
      POSTGRES_DB: hw28-db
    volumes:
      - hw28data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  hw28data:
