spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/hw28-db
    username: hw28
    password: hw28
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

  flyway:
    enabled: true
    cleanDisabled: false
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5430/hw28-db
    user: hw28
    password: hw28

server:
  port: 8080

debug: true
logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
