spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5430/demoDB
    user: usr
    password: pwd

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
