version: "3.8"

services:
  db:
    image: postgres:13
    container_name: hw38-docker
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB
    volumes:
      - hw38data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  hw38data:
